version: '2'
services:
  jekyll:
    image: ruby:2.4
    command: sh -c "bundle install && bundle exec jekyll serve --destination /tmp --host 0.0.0.0"
    volumes:
      - ".:/usr/src/app"
    ports:
      - "4000:4000"
    working_dir: "/usr/src/app"
